<?php defined('SYSPATH') or die('No direct script access.'); 
 return  array(
     0 => array(
         "id" => "1",
         "name" => "少林足球",
         "short_name" => "shaolinzuqiu",
         "parent_id" => "-1",
         "sort" => "0",
         "parent_name" => NULL,
         "has_child" => TRUE,
    ),
     1 => array(
         "id" => "2",
         "name" => "游戏",
         "short_name" => "games",
         "parent_id" => "-1",
         "sort" => "0",
         "parent_name" => NULL,
         "has_child" => TRUE,
    ),
     2 => array(
         "id" => "6",
         "name" => "植物大战僵尸",
         "short_name" => "pvz",
         "parent_id" => "2",
         "sort" => "0",
         "parent_name" => "游戏",
         "has_child" => FALSE,
    ),
     3 => array(
         "id" => "7",
         "name" => "巫妖王之怒",
         "short_name" => "dk",
         "parent_id" => "4",
         "sort" => "0",
         "parent_name" => "魔兽世界",
         "has_child" => FALSE,
    ),
     4 => array(
         "id" => "8",
         "name" => "燃烧的远征",
         "short_name" => "fire",
         "parent_id" => "4",
         "sort" => "0",
         "parent_name" => "魔兽世界",
         "has_child" => FALSE,
    ),
     5 => array(
         "id" => "4",
         "name" => "魔兽世界",
         "short_name" => "wow",
         "parent_id" => "2",
         "sort" => "50",
         "parent_name" => "游戏",
         "has_child" => TRUE,
    ),
     6 => array(
         "id" => "9",
         "name" => "11111",
         "short_name" => "111133",
         "parent_id" => "1",
         "sort" => "50",
         "parent_name" => "少林足球",
         "has_child" => FALSE,
    ),
     7 => array(
         "id" => "10",
         "name" => "6666881",
         "short_name" => "666644",
         "parent_id" => "2",
         "sort" => "50",
         "parent_name" => "游戏",
         "has_child" => FALSE,
    ),
     8 => array(
         "id" => "5",
         "name" => "魔兽争霸",
         "short_name" => "war3",
         "parent_id" => "2",
         "sort" => "51",
         "parent_name" => "游戏",
         "has_child" => FALSE,
    ),
) ;
?>